// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd2e0R9d6R9E98rXIznGyWfbuTAhWXcJQ',
    appId: '1:863872732054:web:4d252ff4eb42cd8530abb7',
    messagingSenderId: '863872732054',
    projectId: 'trumbien',
    authDomain: 'trumbien.firebaseapp.com',
    storageBucket: 'trumbien.appspot.com',
    measurementId: 'G-EWD941CVYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrZpW2DocuYspAPfq7FS8kK4nJl1U9Rew',
    appId: '1:863872732054:android:37cbaf88c766da1530abb7',
    messagingSenderId: '863872732054',
    projectId: 'trumbien',
    storageBucket: 'trumbien.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmAbEXoFicYt1h1KxL5deAX7doWpeSsRQ',
    appId: '1:863872732054:ios:b683ba5be5dc140c30abb7',
    messagingSenderId: '863872732054',
    projectId: 'trumbien',
    storageBucket: 'trumbien.appspot.com',
    androidClientId: '863872732054-ah056vc8o6gbpo32sol13nfmt832bm2h.apps.googleusercontent.com',
    iosClientId: '863872732054-n1rgr0t76om9n3b160rvoad34os5fapp.apps.googleusercontent.com',
    iosBundleId: 'com.example.productSell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmAbEXoFicYt1h1KxL5deAX7doWpeSsRQ',
    appId: '1:863872732054:ios:b683ba5be5dc140c30abb7',
    messagingSenderId: '863872732054',
    projectId: 'trumbien',
    storageBucket: 'trumbien.appspot.com',
    androidClientId: '863872732054-ah056vc8o6gbpo32sol13nfmt832bm2h.apps.googleusercontent.com',
    iosClientId: '863872732054-n1rgr0t76om9n3b160rvoad34os5fapp.apps.googleusercontent.com',
    iosBundleId: 'com.example.productSell',
  );
}
